---
abstract: 'Lexically scoped sanctification of %ENV'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.88'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Env-Sanctify
no_index:
  directory:
    - examples
    - inc
    - t
provides:
  Env::Sanctify:
    file: lib/Env/Sanctify.pm
    version: 1.04
requires:
  perl: 5.6.0
resources:
  homepage: http://github.com/bingos/env-sanctify/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bingos/env-sanctify.git
version: 1.04
